### ISSUE TITLE
Mapbox not working

### ISSUE THREAD

**Issue by kosvrouvas** [juaneladio/metropolitano#16]
Hi, mapbox.js loads without problems but map never loads.

**Comment by kosvrouvas** [comment]
anyone?

**Comment by juaneladio** [comment]
Hi, I didn't received any notification about this bug. 
A temporal fix was placed: I added L.mapbox.tileLayer('examples.map-i86nkdio'); 
but I guess I need to set an Access Token https://www.mapbox.com/mapbox.js/api/v2.1.0/api-access-tokens/

**Comment by kosvrouvas** [comment]
Hi, not a problem @juaneladio! Yes that was the case, you need an Access Token but forgot to mention it here.

**Comment by juaneladio** [comment]
I updated the source code with the required token and tile (from a Project in Mapbox)
https://github.com/juaneladio/metropolitano/commit/bee2eb490a1c385f73ba2e7002c378078a92bb9c
